#!/bin/bash
for i in `seq 0 9`;
do
  echo $i
  convert falling_01_0000$i.png -resize 25% falling_01_$i.png
  convert falling_01_0000$i.png -resize 50% falling_01_$i@2x.png
done

for i in `seq 10 17`;
do
  echo $i
  convert falling_01_000$i.png -resize 25% falling_01_$i.png
  convert falling_01_000$i.png -resize 50% falling_01_$i@2x.png
done
